name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: test_user
      DB_PASSWORD: test_pass
      DB_NAME: test_db
      JWT_TOKEN: my_test_jwt_secret
      JWT_EXPIRES_IN: 3600s
      JWT_REFRESH_TOKEN: my_test_refresh_jwt_secret
      JWT_REFRESH_EXPIRES_IN: 7d
      REFRESH_TOKEN_HASH_SECRET: my_test_refresh_token_hash_secret
      JWT_EMAIL_VERIFICATION_SECRET: my_test_email_verification_secret
      JWT_EMAIL_VERIFICATION_EXPIRES_IN: 1d
      RABBITMQ_URL: amqps://wfndvqhu
      RABBITMQ_EXCHANGE: social_media_exchange

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - run: npm run test:e2e